spellername = "Czech"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Czech spellchecker"
cs = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Czech, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
cs = "TRANSLATE: A spellchecker for Czech, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.cs"

[windows]
system_product_code = "{867CD165-73BF-4FA9-B513-333FB4C947C5}_is1"
legacy_product_codes = [
    { value = "CC3E6206-CD18-4164-B9F0-B71174D6B2E9", kind = "nsis" },
    { value = "0DFC2F6D-F4D9-4136-A836-B225BC94872A", kind = "nsis" }
]
