template = "https://github.com/giellalt/template-lang-und"
rev_id = 328
template_sha = "a66ce6606ea33e46cd3439c88cafa44d4dcdde92"

[replacements]
__GLOTTOLOG_ID__ = "czec1258"
__REPO__ = "lang-ces"
__UND2C__ = "cs"
__UNDEFINED__ = "Czech"
__UND__ = "ces"
