template = "https://github.com/giellalt/template-lang-und"
rev_id = 332
template_sha = "517a754a9d968919fdaa1ed6e00d20145fac402c"

[replacements]
__GLOTTOLOG_ID__ = "czec1258"
__REPO__ = "lang-ces"
__UND2C__ = "cs"
__UNDEFINED__ = "Czech"
__UND__ = "ces"
