[package]
name = "ces"
human_name = "Czech"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.ces]
filename = "cs-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-ces"
platform = "windows"
uuid = "CC3E6206-CD18-4164-B9F0-B71174D6B2E9"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.cs"
package = "speller-ces"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-ces-mso"
platform = "windows"
uuid = "0DFC2F6D-F4D9-4136-A836-B225BC94872A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-ces"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
